'use client';
import { useState } from 'react';
import { ChatApp, AnimatedSidebar, AnimatedSidebarContent, AnimatedSidebarHeader, AnimatedSidebarTrigger } from '@/components/asharca/agent-chat-app';
import { AISidebar } from '@/components/asharca/agent-sidebar';
import { Message, MessageAvatar, MessageContent, MessageHeader, MessageGroup } from '@/components/asharca/agent-message';
import { MessageBubble, MessageBubbleContent } from '@/components/asharca/agent-message-bubble';
import { MessageScroller } from '@/components/asharca/agent-message-scroller';
import { PromptInput } from '@/components/asharca/agent-prompt-input';
import { StreamingResponse } from '@/components/asharca/agent-streaming-response';
import { TodoList } from '@/components/asharca/agent-todo-list';
import { SafeStreamdown } from '@/components/asharca/safe-streamdown';
type Entry = { id: string; from: 'user' | 'assistant'; content: string };
export default function Demo() { const [messages, setMessages] = useState<Entry[]>([{ id: 'u0', from: 'user', content: '展示迁移进度。' }, { id: 'a0', from: 'assistant', content: '| 阶段 | 状态 |\n| --- | --- |\n| 源码适配 | 已完成 |\n| 测试验证 | 进行中 |' }]); const [active, setActive] = useState('current');
return <ChatApp className="h-[560px] w-full max-w-5xl" sidebarWidth="13rem"><AnimatedSidebar collapsible="offcanvas" className="h-full" panelClassName="h-full" ariaLabel="Agent 会话"><AnimatedSidebarHeader><span className="p-2 text-sm font-semibold">Agent 工作区</span></AnimatedSidebarHeader><AnimatedSidebarContent><AISidebar defaultItems={[{ id: 'project', label: '组件项目', kind: 'project', children: [{ id: 'current', label: '当前任务', kind: 'file' }] }]} defaultExpandedIds={['project']} activeId={active} onActiveChange={setActive} /></AnimatedSidebarContent></AnimatedSidebar><div className="flex min-w-0 flex-1 flex-col"><header className="flex items-center gap-2 border-b border-border p-2"><AnimatedSidebarTrigger aria-label="切换 Agent 会话导航">☰</AnimatedSidebarTrigger><span className="text-sm font-medium">组件迁移助手</span><span className="ml-auto pr-2 text-[10px] text-muted-foreground">本地演示</span></header><MessageScroller className="min-h-0 flex-1" label="Agent 对话" viewportClassName="p-4"><MessageGroup>{messages.map((entry) => <Message key={entry.id} id={entry.id} from={entry.from} animateIn><MessageAvatar>{entry.from === 'user' ? '我' : 'AI'}</MessageAvatar><MessageContent><MessageHeader>{entry.from === 'user' ? '你' : '开发助手'}</MessageHeader><MessageBubble variant={entry.from === 'user' ? 'solid' : 'ghost'}><MessageBubbleContent>{entry.from === 'assistant' ? <StreamingResponse status="complete" copyText={entry.content}><SafeStreamdown allowMermaid>{entry.content}</SafeStreamdown></StreamingResponse> : entry.content}</MessageBubbleContent></MessageBubble></MessageContent></Message>)}</MessageGroup><div className="mt-4"><TodoList title="检查清单" items={[{ id: 'source', title: '读取组件源码', status: 'completed' }, { id: 'test', title: '验证交互', status: 'in-progress', progress: 60 }]} /></div></MessageScroller><div className="shrink-0 border-t border-border p-3"><PromptInput aria-label="Agent 对话输入" placeholder="输入内容，查看本地回复…" minRows={1} models={[{ value: 'demo', label: '本地演示' }]} onSubmit={async (text) => { setMessages((all) => [...all, { id: `u${all.length}`, from: 'user', content: text }, { id: `a${all.length}`, from: 'assistant', content: '已收到。这是本地示例，实际模型请求由你的应用提供。' }]); }} /></div></div></ChatApp>; }
